name: Benchmark

on:
  #  push:
  #    branches: [ main ]
  #    paths-ignore:
  #      - '**.md'
  #      - 'demo/**'
  #      - 'docs/**'
  #  pull_request:
  #    types: [ opened, synchronize, reopened ]
  #    paths-ignore:
  #      - '**.md'
  #      - 'demo/**'
  #      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout sources
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with: { persist-credentials: false }

      - name: Check benchmark
        run: cargo bench
